- openstack-heat/caasp-stack.yaml
Add a Heat Template for booting CaaSP
> Add CaaSP OpenStack Heat Template

- velum-bootstrap/Gemfile
- velum-bootstrap/Gemfile.lock
> re-add rack to Gemfile

- .gitignore
- velum-bootstrap/Gemfile
- velum-bootstrap/Gemfile.lock
- velum-bootstrap/spec/spec_helper.rb
for generating jenkins testreports we can use `rspec_junit_formatter`
> add junit formatter

- velum-bootstrap/spec/features/bootstrap_cluster.rb
admin node was nil element in array
> enhance query and compact array

- velum-bootstrap/spec/features/bootstrap_cluster.rb
> drop workaround

- velum-bootstrap/.gitignore
- velum-bootstrap/spec/features/bootstrap_cluster.rb
- velum-bootstrap/spec/spec_helper.rb
- velum-bootstrap/spec/support/helpers.rb
> save screenshots

- velum-bootstrap/spec/features/bootstrap_cluster.rb
- velum-bootstrap/spec/spec_helper.rb
- velum-bootstrap/spec/support/helpers.rb
> save screenshot after error and timeout

- velum-bootstrap/spec/features/bootstrap_cluster.rb
there are some flaky tests which are probably related to
https://bugzilla.suse.com/show_bug.cgi?id=1050450
for our CI we decided to add this workaround until the bug
is fixed
I am still not sure this fixes the issue, we can run the CI multiple times to be sure
Run1: http://jenkins.caasp.suse.net/blue/organizations/jenkins/automation/detail/PR-31/2/pipeline
Run2: http://jenkins.caasp.suse.net/blue/organizations/jenkins/automation/detail/PR-31/3/pipeline
Run3: http://jenkins.caasp.suse.net/blue/organizations/jenkins/automation/detail/PR-31/4/pipeline
> workaround: refresh page

- jenkins-pipelines/Jenkinsfile.image-cacher
Additionally, add a few stages and a workspace cleanup step to make
the UI a little cleaner.
> Image Cacher: Ensure we checkout the correct branch

- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
This will fail for the moment, as the OpenStack CI implementation
isn't ready, however it will start working once that lands.
> Add a nightly 50 node OpenStack job

- caasp-devenv
- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf
- caasp-kvm/start.sh
- caasp-kvm/tools/generate_environment.sh
Add a wrapper script to handle using all these tools quickly and easily.
We shouldn't put too much in here, if you need to customise the args passed to each tool, you should use the tool directly.
> Add tooling wrapper script

- k8s-e2e-tests/Dockerfile
- k8s-e2e-tests/e2e-tests
needs backport to `release-1.0` with different obs path/base image
> Dockerfile: use obs development repo and leap 42.3

- k8s-e2e-tests/entrypoint.sh
Compute number of Kubernetes ready cluster nodes and
adjust number of tests that can run in parallel depends on
what tests are running and on the size of the cluster.
Too many, and tests will fail due to resource contention.
> Tune number of tests that can run in parallel

- k8s-e2e-tests/entrypoint.sh
Compute number of Kubernetes ready cluster nodes and
adjust number of tests that can run in parallel depends on
what tests are running and on the size of the cluster.
Too many, and tests will fail due to resource contention.
(cherry picked from commit 903e1eceb8903e9af77f1762976d7bb5e4463a81)
> [release-1.0] Tune number of tests that can run in parallel

- caasp-openstack/README.md
- caasp-openstack/caasp-cluster.tf
- caasp-openstack/caasp-openstack
- caasp-openstack/cloud-init.adm
- caasp-openstack/cloud-init.cls
- caasp-openstack/openstack.tfvars
We would like to have CaaSP installation on OpenStack automated, terraform based can help with that.
> Add terraform orchestration for CaaSP deployment on OpenStack cloud

- caasp-openstack/README.md
- caasp-openstack/caasp-cluster.tf
- caasp-openstack/caasp-openstack
- caasp-openstack/cloud-init.adm
- caasp-openstack/cloud-init.cls
- caasp-openstack/openstack.tfvars
backport of https://github.com/kubic-project/automation/pull/30
> [1.0] Add terraform orchestration for CaaSP deployment on OpenStack cloud

- caasp-kvm/cluster.tf
- caasp-kvm/terraform.tfvars.example
Set admin node to 3GB of RAM and 4 vCPU
> KVM: Update admin node resources

- caasp-devenv
- caasp-kvm/terraform.tfvars.example
- caasp-openstack-heat/caasp-stack.yaml
See commit messages for details
> Several Cleanup Commits

- velum-bootstrap/spec/features/bootstrap_cluster.rb
Ensure the page has fully loaded before moving on
> Another velum-bootstrap reliability fix

- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf
- caasp-kvm/tools/download_image.py
This makes the output much more pleasant (e.g. wget output).
Additionally, fix download script to cleanup failed/partial downloads.
> Move local steps from TF -> caasp-kvm script

- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
Additionally, set worker count to 25
> Run K8S Tests on Nightly OpenStack Job

- caasp-kvm/cluster.tf
- caasp-kvm/tools/generate_environment.sh
- velum-bootstrap/spec/features/bootstrap_cluster.rb
Three commits to fix booting multi master with caasp-kvm / velum-bootstrap.
> Multi Master Fixes

- velum-bootstrap/spec/features/01-setup-velum.rb
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Split sequence in two and add some waiting to prevent races.
Stop downcasing hostnames.
> Split bootstrap_cluster.rb in two phases

- caasp-kvm/tools/generate_environment.sh
This allows for valid and working certificates when using multi-master
deployments.
> KVM: Use real DNS names for Kube-API endpoint

- .gitignore
- caasp-devenv
- velum-bootstrap/.bundle/config
This helps to not pollute the system gems.
> Execute `bundle install` with `--path .bundler` so no gems are installed in the system

- caasp-devenv
- velum-bootstrap/velum-interactions
As new specs are added for upgrade, we want to ensure only the correct
specs are called at the correct time.
> Add a velum-bootstrap wrapper script

- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
Backport of https://github.com/kubic-project/automation/pull/108
> [1.0] Fix K8S Conformance Nightly

- misc-tools/download_image.py
Additionally, create a static path for docker images too
> Add OpenStack and ISO image support to download tool

- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
- misc-tools/download_image.py
> Backports 1.0

- caasp-devenv
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/velum-interactions
Add support for enabling tiller during dev env creation
> Add support for Tiller

- caasp-bare-metal/README.md
- caasp-bare-metal/deployer/deploy_testbed.py
- caasp-bare-metal/deployer/deployer
- caasp-bare-metal/deployer/environment_json.py
- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
Add bare metal deployment together with https://github.com/kubic-project/jenkins-library/pull/80
> Add bare metal deploy script

- caasp-bare-metal/deployer/deploy_testbed.py
Related to https://github.com/kubic-project/velum/pull/270
> Remove credentials error from autoyast file

- caasp-bare-metal/deployer/environment_json.py
Set kubernetesHost to the master ipaddr
> Fix master node ipaddr

- caasp-bare-metal/deployer/deploy_testbed.py
This reverts commit 54363823800024e0301cba0b35e3d97a745b547f.
Depends on: https://github.com/kubic-project/velum/pull/311
> Revert "Remove credentials error from autoyast file"

- jenkins-pipelines/Jenkinsfile.image-loader-openstack
- misc-tools/upload-image-openstack.sh
Loads CaaSP images into Provo OpenStack Cloud
> Openstack Image Loader

- caasp-openstack-heat/.gitignore
- caasp-openstack-heat/caasp-openstack
- caasp-openstack-heat/tools/generate-environment
Heat: Small tracking fix, update support
> Heat: Small tracking fix, update support

- caasp-openstack-heat/.gitignore
- caasp-openstack-heat/caasp-openstack
- caasp-openstack-heat/caasp-stack-master.yaml
- caasp-openstack-heat/caasp-stack-worker.yaml
- caasp-openstack-heat/caasp-stack.yaml
- caasp-openstack-heat/tools/generate-environment
Builds on https://github.com/kubic-project/automation/pull/123
> Heat: Add multi master support

- caasp-bare-metal/deployer/deploy_testbed.py
Fetch new ISO using the BMM in a 2-step process: start fetching the ISO and wait for the download to complete.
> Bare metal: fetch new ISO

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Depends on: https://github.com/kubic-project/velum/pull/314
> Fix kubeconfig download workflow

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Also, make the test less flaky by doing the proper waits.
> Visit the root before trying to download the kubeconfig file

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Part of bsc#1062291
Depends-On: https://github.com/kubic-project/velum/pull/322
Depends-On: https://github.com/kubic-project/salt/pull/251
> Fill in Dashboard's external FQDN during bootstrap

- caasp-bare-metal/deployer/deploy_testbed.py
Prevent assertion error when run with --start-iso-fetching only
> Bugfix: move assertion

- misc-files/download-urls.json
- misc-tools/download-image
Add configuration file to be used by misc-tools/download-image and caasp-bare-metal/deployer/ in future
> Add download-urls.json

- caasp-bare-metal/deployer/deploy_testbed.py
Backport from master
Backport of https://github.com/kubic-project/automation/pull/177
> [2.0] Update admin ipaddr in environment.json

- caasp-bare-metal/deployer/environment_json.py
- caasp-kvm/caasp-kvm
- caasp-kvm/tools/generate-environment
- caasp-openstack-heat/caasp-openstack
- caasp-openstack-heat/tools/generate-environment
- environment.json.example
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/spec_helper.rb
Store internal vs external hostnames within environment.json, as these are needed now and currently being "hacked" in..
> External hosts

- caasp-kvm/README.md
- caasp-kvm/tools/build-velum-image
- caasp-kvm/tools/fix-kubelet-manifest
This is a try to fix the rspec devenv in a slightly different way than proposed in https://github.com/kubic-project/automation/pull/180.
It's another PR just for the purpose of discussing both cleanly.
Depends on: https://github.com/kubic-project/velum/pull/378
Supersedes: https://github.com/kubic-project/automation/pull/180
Supersedes: https://github.com/kubic-project/velum/pull/372
> Fix rspec devenv

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
> Increase node loading timeouts

- caasp-openstack-heat/caasp-openstack
Ignored SC1090 - seems to be working in bash
Ignored SC2046 on line 133 - is web URL
Ignored SC2155 - no return values are masked
Script uses non-POSIX-compliant features, so changed shebang to reference bash.
Quoted lots of un-quoted string variables
> OpenStack Heat - Run shellcheck, and fix issues

- k8s-pod-tests/README.md
- k8s-pod-tests/k8s-pod-tests
- k8s-pod-tests/yaml/default.yml
> Add pod scaling scripts and confs

- caasp-bare-metal/deployer/deploy_testbed.py
Backport of #204 cae4be9fd5b51ded909077da622034323c829d7e
> Tidy up action logic

- testinfra/tests/test_kubernetes_worker.py
As we are removing our machine-id hostnames, we'll need to support
both machine-id and unique-hostname for a short period of time. Add
support to check for either/or in tests that need it.
Once the machine-id hostnames patches have merged elsewhere, the
compatibility code here should be removed.
> Testinfra: Allow for non machine-id hostnames

- caasp-kvm/README.md
- reordered instructions assume a fresh SUSE install
- fix libvirt group
- add virsh storage pool instructions
> caasp-kvm: update test cluster setup instructions

- caasp-openstack-heat/README.md
- caasp-openstack-heat/caasp-openstack
- caasp-openstack-heat/caasp-stack-master.yaml
- caasp-openstack-heat/caasp-stack-worker.yaml
- caasp-openstack-heat/caasp-stack.yaml
- caasp-openstack-heat/heat-environment.yaml.example
- caasp-openstack-heat/tools/generate-environment
- caasp-openstack-heat/volume-with-attachment.yaml
Backports several changes from master -> release-2.0. All related to the caasp-openstack-heat tool.
> Heat: Backports to 2.0

- misc-tools/supportutils-parser
> Improve Salt event failure filtering

- misc-tools/supportutils-parser
Allow Jenkink's Blue Ocean to display the file contents
> supportutils-parser: switch output file to .txt

- jenkins-pipelines/Jenkinsfile.kubic-nightly
Depends-On: https://github.com/kubic-project/jenkins-library/pull/121
> KVM Nightly: Set vanilla flag

- velum-bootstrap/spec/spec_helper.rb
- velum-bootstrap/velum-interactions
Velum Bootstrap: environment.json path fixes / additions
>  Velum Bootstrap: environment.json path fixes / additions

- jenkins-pipelines/Jenkinsfile.workers-rotation
> Add NonCPS annotation

- jenkins-pipelines/Jenkinsfile.workers-rotation
> Enable terminate, refactor

- caasp-kvm/cluster.tf.erb
just a minor fix in the description of the caasp_domain_name var
> fix caasp_domain_name description

- caasp-bare-metal/deployer/deploy_testbed.py
Move to a new API call to create worker_mangled.xml to provide disambiguation.
> Add syslog log collection, improve autoyast

- jenkins-pipelines/Jenkinsfile.kubic-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
This isn't full upgrade CI - hence I've not touched any jobs that are upgrade specific.
> Run the pseudo update tests nightly

- caasp-devenv
- caasp-kvm/README.md
- caasp-kvm/caasp-kvm
- misc-tools/download-image
- misc-tools/inject_repo.sh
> enable adding custom repos to the master/workers

- k8s-pod-tests/k8s-pod-tests
Leaving the adaptive function around as it can be used for large number of pods
> Speed up/simplify pod scaling

- caasp-bare-metal/deployer/deploy_testbed.py
Related to 69dd2c3e7cf795a5cbc333a0fba360f8a15b0c8a
> Update URL list format handling

- ses-openstack-terraform/deepsea.sh
- ses-openstack-terraform/ses-cluster.tf
adding openattic on a mon node, security group and floating ip
> adding openattic on a mon node, security group and floating ip

- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-remove
https://github.com/kubic-project/jenkins-library/pull/151
> postBootstrapBody got dropped

- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
> fix addNode job name

- velum-bootstrap/spec/features/07-node-remove.rb
> respect topology warning

- velum-bootstrap/spec/features/07-node-remove.rb
> expect a modal when recommended cluster topology is broken

- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf.erb
This will give us tho option to use a bridged network interface and DHCP addresses for terraform deploys.
> Add terraform bridged networking option

- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade
Without this, it seems it wasn't running any of the job specific steps :(
> Add empty preBootstrapBody to all periodic jenkinsfiles

- velum-bootstrap/spec/features/07-node-remove.rb
> correctly check for failed node removal

- caasp-kvm/tools/cleanup.sh
- k8s-pod-tests/yaml/default.yml
- misc-tools/download-image
- ses-openstack-terraform/ses-cluster.tf
- ses-openstack-terraform/ses-openstack
Matches https://github.com/kubic-project/automation/pull/303
> [2.1] Some backports to 2.1

- jenkins-pipelines/Jenkinsfile.kubic-sandbox
> fix env check

- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
terraform will recreate all vm's otherwise
> opt out of disabling meltdown/spectre fixes

- README.md
- caasp-devenv
- caasp-kvm/README.md
- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf.erb
- caasp-kvm/tools/build-velum-image
- misc-files/download-urls.json
- misc-files/registry-urls.json
- misc-tools/download-image
> add a kubic channel

- caasp-kvm/README.md
> update README to match kubic development environments

- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-remove
This allows tasks which mutate the environment to return
a replacement environment object for use by future steps.
> Return environment from add/remove closures

- caasp-devenv
add gcc and ruby-devel for fixing nokogiri rubygem building
> add gcc and ruby-devel for fixing nokogiri rubygem building

- misc-tools/netdata/capture/README.md
- misc-tools/netdata/capture/capture-charts
- misc-tools/netdata/capture/capture.py
- misc-tools/netdata/install
Install Netdata on admin or master nodes for testing and debugging.
> Add Netdata installer and metrics collector

- misc-tools/network-emulation
Related to https://github.com/kubic-project/jenkins-library/pull/168
> Add network emulation using Traffic Control

- caasp-kvm/caasp-kvm
yaml file in else doesn't exit anymore
> remove todo since pr135 referenced got merged

- caasp-hyperv/caasp-hyperv.ps1
I have added a small cleanup after an image is fetched because keeping vhdfixed.* files is not necessary.
> Minor fix in image fetch/delete

- caasp-kvm/tools/fix-kubelet-manifest
> Patch init containers too, not only regular containers

- caasp-kvm/caasp-kvm
- caasp-kvm/tools/build-velum-image
it can be that a full path contains kubic
> check basename of image

- misc-files/download-urls.json
- misc-files/registry-urls.json
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>
> Update urls to release-3.0

- misc-tools/netdata/install
Just a quick add so we can install netdata on the worker nodes too
> Add worker in target host for netdata

- misc-tools/netdata/capture/capture.py
Prevent host locale from breaking file read
> Add UTF-8 handling in file read

- jenkins-pipelines/Jenkinsfile.kubic-sandbox
> 4.0 bump for the SandBox pipeline

- velum-bootstrap/spec/features/04-upgrade-admin.rb
Testing it on https://github.com/kubic-project/jenkins-library/pull/170 with https://github.com/kubic-project/velum/pull/520 and https://github.com/kubic-project/salt/pull/424
> Perform longer wait for the admin reboot (20 minutes max)

- velum-bootstrap/spec/features/04-upgrade-admin.rb
(cherry picked from commit 8ebbc750d6c5e799d03ddeba21207f31e70ad0dd)
Backport of https://github.com/kubic-project/automation/pull/385
> [3.0] Perform longer wait for the admin reboot (20 minutes max)

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/features/05-upgrade-minions.rb
- velum-bootstrap/spec/features/06-node-add.rb
- velum-bootstrap/spec/features/07-node-remove.rb
- velum-bootstrap/spec/spec_helper.rb
afterall there were still some flaws ... :crying_cat_face:
> moar node removal fixes and some DRY cleanup

- caasp-kvm/README.md
Updated README.md under caasp-kvm to be accurate to current proper process for setting up and getting a cluster running.
> Update caasp-kvm readme

- README.md
- misc-tools/extract-kernel-initrd-cmdline-args
Send virt-cat -h output do /dev/null
Improve README.md with development tips
> Silence virt-cat, update readme

- jenkins-jobs/projects.yaml
This just adds the housekeeping job for now.
> Generate a new job for velum-branding repo

- caasp-bare-metal/deployer/environment_json.py
Bug found while testing #416 on BM
> Fix environmnent.json indexes

- Jenkinsfile.jenkins-jobs
- jenkins-jobs/README.md
- jenkins-jobs/jobs.yaml
Add the first of the nightly jobs to JJB - Just `caasp-nightly` for now.
> Add caasp-nightly to JJB & add test+upload job

- misc-tools/download-image
otherwise docker, k8s etc are not installed
follow up of https://github.com/kubic-project/automation/pull/400
@bergmannf sorry i missed that in the review
> fetch stack image

- k8s-e2e-tests/e2e-tests
cluster
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>
(cherry picked from commit 49bdb3dc16fb65770c718270e049acce0fffe482)
> Increase k8s e2e tests timeout cause this is not enought on our test

- ses-openstack-terraform/deepsea.sh
- ses-openstack-terraform/openstack.tfvars
- ses-openstack-terraform/ses-cluster.tf
Fix ses deployment script, the ses guys changed some pillar data i was relying on.
Changed default osd size from 1gb to a more realistic 40gb
Changed default instance size from medium to large
> Fix ses deployment script

- ses-openstack-terraform/admin.tpl
- ses-openstack-terraform/deepsea.sh
- ses-openstack-terraform/mon.tpl
- ses-openstack-terraform/openstack.tfvars
- ses-openstack-terraform/osd.tpl
- ses-openstack-terraform/ses-cluster.tf
Signed-off-by: Alexandru Bonini <boninialexandru@gmail.com>
> changed from sles pool/update repos to scc and regcode and osd pool to 45 45

- testinfra/tests/test_kubernetes_master.py
> adapt testinfra to respect removed nodes

- k8s-e2e-tests/e2e-tests
> adapt to the new sonobuoy workflow

- .gitignore
- Jenkinsfile.codenarc
- jenkins-jobs/job-templates.yaml
- jenkins-jobs/projects.yaml
Relates to https://github.com/kubic-project/jenkins-library/pull/203
> Add codenarc to jenkins-library/automation - Static Analysis for Groovy

- k8s-e2e-tests/e2e-tests
> sonobuoy is now part of the worker

- misc-tools/download-image
Allows exploring image contents
> Add link to the package version tracker

- caasp-devenv
> terraform packages have moved

- caasp-bare-metal/deployer/deploy_testbed.py
Make logging around DHCP and SSH more informative and less verbose
> Bare metal deployer: improve logging

- caasp-bare-metal/deployer/deploy_testbed.py
Make logging around DHCP and SSH more informative and less verbose
> [backport PR #473] Improve logging

- misc-tools/parallel-ssh
- misc-tools/parallelssh/tool.py
- misc-tools/setup-python
Add tool to run ssh in parallel and stream output in realtime.
Add helper to install Python virtualenv and dependencies.
> Add parallel ssh

- caasp-kvm/README.md
- caasp-kvm/caasp-kvm
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
Otherwise I'm getting:
```
$ ./caasp-kvm --help
./caasp-kvm: 3: set: Illegal option -o pipefail
```
> caasp-kvm: Update usage in README and fix shebang

- jenkins-jobs/jobs.yaml
Updates the jobs.yaml to include the new e2e nightly jobs
> Add e2e nightly jobs

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Fixes test cases that changed with the update of the UI.
Blocks: [velum  pr](https://github.com/kubic-project/velum/pull/671)
> FIX bsc#1099985 remove and reject nodes

- misc-tools/parallelssh/tool.py
Running parallel-ssh to monitor logs in parallel with running test leads to race conditions in Jenkins.
Add retry logic to ensure the process is found and stopped.
> parallel-ssh: add retry logic during stop

- misc-tools/parallel-ssh
- misc-tools/parallelssh/tool.py
> [Backport PR #500 and #501] Add retry logic

- caasp-kvm/tools/build-velum-image
Adds code to check the curl response before parsing the tags.
> FIX bsc#1101970 check for curl response

- velum-bootstrap/spec/features/01-setup-velum.rb
- velum-bootstrap/spec/support/helpers.rb
The helper function was only used 1 time
this is a backport from a old PR
https://github.com/kubic-project/automation/pull/112
> Remove global function and adapt smaller context

- ses-openstack-terraform/ses-cluster.tf
Signed-off-by: Alexandru Bonini <boninialexandru@gmail.com>
> Fix for printing secret in output variable

- kubic-kvm/.gitignore
- kubic-kvm/README.md
- kubic-kvm/commoninit.cfg
- kubic-kvm/kubic-kvm.tf
backport from  #474  plus other Improvements.
> Kubic kvm first example

- jenkins-pipelines/Jenkinsfile.kubic-nightly-kvm-on-bm
Add experimental KVM on BM pipeline
> [WIP] Add KVM on BM pipeline

- caasp-bare-metal/deployer/deploy_testbed.py
> Bare metal: add 4.0 ISO URL

- jenkins-pipelines/Jenkinsfile.image-cacher
- jenkins-pipelines/Jenkinsfile.image-loader-openstack
Switch image caching pipelines
> Switch to leap15.0

- ses-openstack-terraform/deepsea.sh
> Add keyring on mons

- caasp-kvm/tools/cleanup.sh
Also print out some of the resources before deletion.
> cleanup.sh: delete kvm-devel volume

- caasp-kvm/cluster.tf.erb
backport from : https://github.com/kubic-project/automation/pull/490
cloud_init_disk to reflect upstream api
> [Release-30]: adapt cloudinit api change to

- k8s-pod-tests/k8s-pod-tests
Add retry mechanism to handle failures currently impacting release 3.0
> Handle kubectl scale failures

- caasp-kvm/cluster.tf.erb
- caasp-kvm/disk_caching.xsl
Workaround for etcd errors on release-3.0 pipelines
> [Backport #545] Set disk caching policy to "unsafe"

- tests/.dockerignore
- tests/external_auth_tests/test_external_auth.py
- tests/util/container_info.py
- tests/util/container_tests.py
Fixes for differences between how macOS and leap 15 handle docker images. Also added dockerignore for python cache files.
> Fixes to how container tests are handled

- .github/PULL_REQUEST_TEMPLATE.md
> Add pr template for backport and other things

- misc-tools/list_image_repo.py
> fix exit script on error

- README.md
Corrects the README so hopefully less people get confused about the role of the contents of this repo
Fixes #585
> Clarify this repos role in README.md

- misc-tools/download-image
> Add VMware support

- misc-tools/vmware-image-handler.py
Add a little helper to be used temporarily and then moved to testrunner
> Add VMware image handler

- .github/PULL_REQUEST_TEMPLATE.md
- Remove branch-2.1 references
- Add commit message guidelines
- Add more context to the PR and documentation section
- Fix formatting for issue tracking
> .github: Update PR template

- jenkins-pipelines/Jenkinsfile.image-loader-openstack
- misc-tools/upload-image-openstack.sh
- Fix OpenStack upload tool with new cloud setup
> Switch to devel master

- jenkins-jobs/jobs.yaml
- jenkins-pipelines/Jenkinsfile.kube-scaling-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
- jenkins-pipelines/Jenkinsfile.kubic-nightly-cri-o
- jenkins-pipelines/Jenkinsfile.kubic-nightly-kvm-on-bm
- jenkins-pipelines/Jenkinsfile.kubic-nightly-network-emulation
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-remove
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade
- jenkins-pipelines/Jenkinsfile.kubic-sandbox
- jenkins-pipelines/Jenkinsfile.kubic-sle15
This job will run the pod scaling tests in a nightly basis.
Remove the scaling tests from the rest of the pipelines.
Depends on https://github.com/kubic-project/jenkins-library/pull/252
> Add a specific scaling pipeline

- caasp-kvm/cluster.tf.erb
we'll likely never use a mirror in the devenv
> hide the outdated RMT/SMT mirror warning in the devenv

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/features/05-upgrade-minions.rb
- velum-bootstrap/spec/features/06-node-add.rb
- velum-bootstrap/spec/features/07-node-remove.rb
- velum-bootstrap/spec/spec_helper.rb
> [3.0] Backport node removal fixes

- caasp-bare-metal/deployer/environment_json.py
Bad conflict resolution, fix environment generation
> [3.0] Fix environmnent.json indexes

- k8s-e2e-tests/e2e-tests
Sometimes sonobuoy retrieve does not work, retry the retrieve command.
> Retry sonobuoy retrieve

- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack-terraform
Fix a typo in the pipeline script
> jeknins-pipelines: openstack-terraform: Fix typo in OpenStack job

- caasp-devenv
- caasp-openstack-terraform/caasp-cluster.tf
- caasp-openstack-terraform/tools/generate-environment
Fixes a problem with openrc parameter and also fixes the node name for openstack-terraform
> Fix node name

- caasp-devenv
Add missing --image option to the script.
> caasp-devevn: Add missing long image option

- velum-bootstrap/.bundle/config
The file is being updated with styling fixes everytime we run the
setup process so just update it to avoid having a dirty git repository
for no reason.
> velum-bootstrap: Update velum configuration file

- ses-openstack-terraform/admin.tpl
- ses-openstack-terraform/deepsea.sh
- ses-openstack-terraform/mon.tpl
- ses-openstack-terraform/openstack.tfvars
- ses-openstack-terraform/osd.tpl
- ses-openstack-terraform/ses-cluster.tf
- ses-openstack-terraform/ses-openstack
- ses-openstack-terraform/terraform.tfvars
- What was wrong with the existing code?
It was using ses hardcoded repos
- How does this PR fixes it?
Now it uses ses registration code
> removed ses hardcoded repos, added ses reg code

- ses-openstack-terraform/openstack.tfvars
- ses-openstack-terraform/ses-cluster.tf
- What was wrong with the existing code?
osd volume size is hardcoded
- How does this PR fixes it?
osd volume size becomes a variable
> replaced hardcoded volume size with a variable

- velum-bootstrap/spec/features/05-upgrade-minions.rb
> Fix feature name

- jenkins-pipelines/Jenkinsfile.image-loader-openstack
- misc-tools/upload-image-openstack.sh
- Backport of #605 for release-3.0 branch
> Fix openstack upload release 3.0
