- k8s-e2e-tests/Dockerfile
- k8s-e2e-tests/README.md
- k8s-e2e-tests/e2e-tests
- k8s-e2e-tests/entrypoint.sh
Automation for upstream Kubernetes end-to-end tests for CaaSP cluster.
To run tests script has to build first, Docker openSUSE based image
with required packages. When Docker image will be ready, it starts
Kubernetes e2e conformance tests and store logs into file.
Please check README.md file for more information.
> Add automation for upstream Kubernetes e2e tests

- velum-bootstrap/spec/features/bootstrap_cluster.rb
capybara throws an exception if it can't find an element right away
and this leads to a failed test immediately
> rescue in case button is not visible at all yet

- k8s-e2e-tests/e2e-tests
In some cases, ,we cannot use `-ti` when doing `docker run` (in particular, in CI)
> Make the 'docker run' flags configurable

- velum-bootstrap/spec/features/bootstrap_cluster.rb
Some tests are failing because of too short timeouts. This PR tries to fix it by increasing the timeouts.
> Increase some timeouts

- velum-bootstrap/spec/features/bootstrap_cluster.rb
when capybara can't find an element it takes more than 5 sec to come
back with an answer, increase the interval to not stress it too much
> flakiness: relax capybara by increasing query intervals

- velum-bootstrap/spec/features/bootstrap_cluster.rb
Waiting a little while for orchestration success, giving the page time
to update.
> Wait for orchestration success

- velum-bootstrap/spec/features/bootstrap_cluster.rb
This works around a possible issue with Puma handling multiple TLS
connections.
> Reintroduce reset_sessions workaround

- openstack-heat/caasp-stack.yaml
The Provo lab uses lots of 192.168 address space, avoid it and default
to 172.28.0.0/24
> Heat: Avoid a CIDR thats in use within Provo

- velum-bootstrap/spec/features/bootstrap_cluster.rb
This will still only bootstrap with 1 master, however it should
allow the multi-master velum change to pass CI and land.
> Update velum-bootstrap for multimaster changes

- k8s-e2e-tests/e2e-tests
- k8s-e2e-tests/entrypoint.sh
New flag: `--no-tty`: do a `docker run` and `docker attach`
Split the `docker run` flags in several env vars.
New flag: `--no-build`: do not try to build the image
Do not try to modify the original `kubeconfig` passed to the `e2e-tests` runner
Do not fail if the certificates are not provided (they could be embeded in the `kubeconfig`)
Generate a unique container name (we could run several instances of this in Jenkins)
The `e2e-tests` runner can be run from a different directory.
Improved cleanups and error control
> Fixes in the e2e tests

- jenkins-pipelines/Jenkinsfile.image-cacher
- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly
Several of the $class statements we used already have pipeline
variants, without the need to construct by hand. Replace these
with the matching pipeline versions.
Additionally, be consistent over the use of tabs v spaces, and
reduce some excessive indentations.
> Replace tasks with pipeline variants

- velum-bootstrap/spec/features/bootstrap_cluster.rb
The "A supported deployment of .. " alert takes time to disapear, and
the button moves as a result. Capybara uses coordinates to trigger a
click, making it possible for us to "misclick" if the button moves
> Wait for page to settle

- velum-bootstrap/spec/features/bootstrap_cluster.rb
I've just updated the selectors to reflect the change on velum for the current specs. No use case was added for the multiple master selection itself. Lemme if know if that's necessary or not.
Depends-On: https://github.com/kubic-project/velum/pull/278
> velum-bootstrap: spec updated based on multiple master selection

- caasp-openstack-heat/caasp-stack.yaml
There is a redirect in place from 80->443, allow access to this
when building the stack with Heat
> Heat: Allow traffic to port 80

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/support/helpers.rb
Since https://github.com/kubic-project/velum/pull/276 we no longer have
the Kubernetes apiserver FQDN field at the first page of the setup, and we
have an extra step after selecting roles to set this field.
Adapt the workflow on this tests to match the new workflow.
> Update Velum e2e-tests workflow

- misc-tools/download_image.py
This is no longer necessary, as the docker image filenames now include
a build number. Remove this code to keep the codepath the same, and allow
the shasum to handle the verifications.
> Remove downloader etag code

- misc-tools/download_image.py
Rather than having to maintain these lists across every branch, we just maintain them on the branch for the matching version of CaaSP.
This lines up with all our other tools, where master only cares about master (currently 2.0), and release-1.0 only cares about 1.0
> Don't try and support multiple CaaSP versions

- velum-bootstrap/spec/features/03-upgrade-admin.rb
- velum-bootstrap/spec/features/04-upgrade-minions.rb
- velum-bootstrap/velum-interactions
Add two new specs to handle upgrading of CaaSP, one for the admin node, and one
for the masters and workers.
Depends-On: https://github.com/kubic-project/jenkins-library/pull/76
> Add specs to update CaaSP

- jenkins-pipelines/Jenkinsfile.image-cacher
The download tool moved, and it's params, changed
> Fix image-cache job

- jenkins-pipelines/Jenkinsfile.image-cacher
The download tool moved, and it's params, changed
> [1.0] Fix image-cache job

- caasp-openstack-heat/caasp-stack.yaml
- caasp-openstack-terraform/caasp-cluster.tf
This is used for worker -> master API access since the HAProxy
change landed.
> Allow port 6444 through secgroups

- caasp-kvm/cloud-init/admin.cfg
- caasp-kvm/cloud-init/master.cfg.tpl
- caasp-kvm/cloud-init/worker.cfg.tpl
In some envs, we're forced to drop the MTU down. Since we can't control this
with terraform's libvirt plugin, we can add it as an early run command with
cloud init. As this is a dev environment tool, a 1400 MTU should be harmless
> KVM: Force VMs MTUs down to 1400

- caasp-openstack-heat/caasp-stack.yaml
For some CI runs (like release-1.0 branch builds), the stack name would end up
containing a period, which is disallowed some in OpenStack resource names. We
fix this by replacing any periods with hyphens.
> Heat: Fix generation of keypair/network names

- caasp-openstack-heat/caasp-stack.yaml
For some CI runs (like release-1.0 branch builds), the stack name would end up
containing a period, which is disallowed some in OpenStack resource names. We
fix this by replacing any periods with hyphens.
Backport of https://github.com/kubic-project/automation/pull/121
> [1.0] Heat: Fix generation of keypair/network names

- caasp-devenv
- caasp-kvm/caasp-kvm
- caasp-kvm/tools/build-velum-image.sh
- jenkins-pipelines/Jenkinsfile.image-cacher
- misc-tools/download_image.py
Setting CAASP_HTTP_PROXY in ~/.bashrc or similar should mean the dev tools will use the proxy to download anything it needs to fetch from NUE etc
Depends-On: https://github.com/kubic-project/jenkins-library/pull/82
> Add HTTP proxy support for dev tools

- misc-tools/download_image.py
Docker images now build in the images_container_base rather
than images_container_derived repos, update the downloader
to match.
> Update downloader for new image location

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Vary the timeouts based on the # of nodes to allow for larger clusters to be deployed
without unnecessarily hitting the timeout.
The second commit removes another unnecessary check which is inherently prone to race conditions.
> Velum Bootstrap: Vary timeouts based on node count

- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
This is useful for when you use Jenkins to build an env, but want
to keep it around for debugging.
> Make environment destruction optional

- caasp-openstack-heat/caasp-stack.yaml
- caasp-openstack-terraform/caasp-cluster.tf
Masters run kube-proxy too, we should allow access to these ports by
default in our tooling.
> Allow accessing masters on the K8S NodePort range, Allow access to admin on 389

- caasp-kvm/README.md
Setup instructions should assume a clean install, not a well-worndeveloper's environment, in order to cover all necessary changes.
These points were derived from a series of failed attempts to install caasp-kvm on a newly installed Leap system, eventually leading to success.
> caasp-kvm: Be more explicit about requirements

- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf
- caasp-kvm/terraform.tfvars.example
The variable specifying the manifests directory is no longer used.
> Remove unused terraform variable

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Also, make the test less flaky by doing the proper waits.
Backport of https://github.com/kubic-project/automation/pull/162
> Visit the root before trying to download the kubeconfig file

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Part of bsc#1062291
Backport of https://github.com/kubic-project/automation/pull/164
> [2.0] Fill in Dashboard's external FQDN during bootstrap

- velum-bootstrap/spec/spec_helper.rb
Velum bootstrap should be using the same name we expect end-users of
CaaSP to use when accessing the cluster.
> Velum-bootstrap should use the correct URL to access Velum

- velum-bootstrap/spec/spec_helper.rb
Velum bootstrap should be using the same name we expect end-users of
CaaSP to use when accessing the cluster.
Backport of https://github.com/kubic-project/automation/pull/170
> [2.0] Velum-bootstrap should use the correct URL to access Velum

- testinfra/requirements.txt
This will help avoid unexpected suprises when upstream projects
release new + incompatible versions.
> Pin all testinfra dependencies

- caasp-bare-metal/deployer/deploy_testbed.py
The FQDN is required during Velum setup.
> Update admin ipaddr in environment.json

- caasp-kvm/.gitignore
Since we are doing a `terraform init`, a `plugins` directory is created
inside `.terraform` resulting in a dirty state of the repository.
> Ignore `.terraform` directory inside `caasp-kvm`

- caasp-openstack-heat/caasp-openstack
when you have deployed multiple stacks this is helpful as the
.stack_name file will be outdated
> caasp-openstack: enable passing name to subcommands

- caasp-bare-metal/deployer/environment_json.py
- caasp-kvm/caasp-kvm
- caasp-kvm/tools/generate-environment
- caasp-openstack-heat/caasp-openstack
- caasp-openstack-heat/tools/generate-environment
- environment.json.example
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/spec_helper.rb
Store internal vs external hostnames within environment.json, as these are needed now and currently being "hacked" in..
Backport of https://github.com/kubic-project/automation/pull/181
> [2.0] External Hosts

- caasp-kvm/README.md
- caasp-kvm/cluster.tf
- caasp-kvm/terraform.tfvars.example
I do all the development on my laptop but I cannot run a caasp cluster because on it because it's not powerful enough.
However I do have a powerful workstation that I can use. By default the devenv creates a cluster located inside of a natted network that is reachable only by the virtualization host.
I could workaround that by using a ssh tunnel, but this is suboptimal, especially when I want to play with applications running on top of the kubernetes cluster.
With this change the VMs are still created inside of a dedicated network managed by libvirt, but they are also reachable by the outside (once a dedicated routing rule is added to the host).
For example, given the hypervisor host ip address is `192.168.1.39` and all the machines are on the `192.168.200.0/24` network, the following …
> Make remote libvirt hosts scenario easier

- caasp-kvm/README.md
- caasp-kvm/cluster.tf
- caasp-kvm/terraform.tfvars.example
We cannot leave the network mode to be "route" by default, otherwise the network will be broken inside of the VMs when the default subnet is being used.
> Make the kvm network mode configurable

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Nodes tends to be accepted more slowly on bare metal.
> Increase timeout on salt accepting minions

- caasp-openstack-heat/tools/generate-environment
For velum-bootstrap tooling to work, it now requires a
'kubernetesExternalHost' field to be present. Add this into the
environment.json file generation in the OpenStack Heat tooling.
Trivially select the first master as the external kubernetes host.
> Add 'kubernetesExternalHost' to Heat environment

- caasp-kvm/caasp-kvm
This allows us to remove the public.yaml / private.yaml hardcodes, which in
turn allows us to split the public / private pods into more specific pods
matching the typical patterns used to deploy workloads in K8S.
See also - https://github.com/kubic-project/caasp-container-manifests/pull/135
> Move manifests into a subdirectory

- caasp-openstack-heat/caasp-stack-worker.yaml
- caasp-openstack-heat/caasp-stack.yaml
- caasp-openstack-heat/heat-environment.yaml.example
- caasp-openstack-heat/volume-with-attachment.yaml
For building applications on CaaSP that leverage host storage, add
ability to specify in the heat environment file that workers can have a
configurable number of disks added with a configurable size. Default is
to add zero disks, and default disk size is 10 GB.
> CaaSP OS Heat: Add optional disks to workers

- caasp-kvm/terraform.tfvars.example
Variables are now set by passing `-var foo=bar` flags to `terraform apply`.
Since these arguments take precedence over the tfvars file, some of the
variables defined inside of this file can be removed.
Signed-off-by: Thomas Hipp <thipp@suse.de>
> clean up tfvars examples

- caasp-openstack-heat/caasp-openstack
- velum-bootstrap/spec/spec_helper.rb
dashboardExternalHost is the name we expect users to access Velum via. We should be using it for bootstrapping Velum.
Additionally, covert stack names to lowercase to match cloud-init behaviour.
> Use dashboardExternalHost instead of admin FQDN for Velum URL

- caasp-openstack-heat/tools/generate-environment
For velum-bootstrap tooling to work, it now requires a
'kubernetesExternalHost' field to be present. Add this into the
environment.json file generation in the OpenStack Heat tooling.
Trivially select the first master as the external kubernetes host.
Backport of https://github.com/kubic-project/automation/pull/193
> [2.0] Add 'kubernetesExternalHost' to Heat environment

- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade-openstack
We currently use a single project for all OS jobs, and when they trigger each
night at the same time, we run out of quota. Add a lock around the outside for
now to ensure only 1 has access to the openstack project at the same time.
> Add a lock around OS jobs

- misc-files/download-urls.json
The release 3.0 project now exists on IBS, so it's time to update
the download URLs to match.
> Update download URLs for 3.0

- velum-bootstrap/spec/spec_helper.rb
This allows for more accurate screenshots during CI runs.
> Load images during Velum bootstrap

- jenkins-pipelines/Jenkinsfile.image-cacher
- jenkins-pipelines/Jenkinsfile.image-loader-openstack
- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade-openstack
Keep at most 31 days of build history for these jobs, which ensures
the history is eventually purged once a job is disabled due to the
removal of it's branch.
> Ensure periodic builds are cleared at EOL

- jenkins-pipelines/Jenkinsfile.workers-rotation
On each run,
- offline workers that are not busy are deleted
- the online worker with longest runtime is put offline so that it will have time to drain and be deleted in one of the next runs.
> Rotate workers automatically

- caasp-kvm/tools/build-velum-image
there seems to be a new behaviour with bundler 1.16.0 that the
gemfile config gets set to whatever working directory it was executed
from
make sure to override it with the correct path to the Gemfile
> fix bundler gemfile config

- caasp-openstack-heat/caasp-stack.yaml
Enable the NTP server on the admin, and allow port 123 access to it so
that masters/workers may sync NTP.
> Heat: Enable admin NTP server

- caasp-kvm/cluster.tf.erb
caasp-kvm with the vanilla flag won't generate a devel velum image, so we shouldn't
be attempting to load it.
> KVM: Don't load devel-docker-images when running vanilla

- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf.erb
This PR adds the option to add a prefix to all the used names for a kvm terraform setup via caasp-kvm. It changes nothing as long as you do not use the --name-prefix option.
There is one issue with this:
The network (caasp_net_network) has to be configurable for this to actually be useful as well.
But I have another way to come around this, which is to have DHCP assigned addresses on a bridged network. That will be the next PR.
> add name-prefix option to make multiple clusters on one kvm host possible

- caasp-openstack-heat/heat-environment.yaml.example
The previous settings were clashing with CaaSP 2.0's default k8s service
network (172.24.0.0). Change this to 172.25.0.0.
> Heat: Change heat environment internal network settings

- caasp-kvm/README.md
- k8s-pod-tests/README.md
- k8s-pod-tests/k8s-pod-tests
- velum-bootstrap/README.md
- velum-bootstrap/velum-interactions
* Add kubeconfig path to environment.json when Velum Bootstrap downloads the file
* Update K8S Pod Tests to use kubeconfig path to environment.json by default
* Snuck in an update of the caasp-kvm README.md section CLI syntax
> Add kubeconfig path to environment.json

- caasp-kvm/tools/generate-environment
This is important for DHCP assigned addresses in a bridged network.
> use reverse dns names for minions

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
This is (obviously) a total hack. We need to fix and fix the underlying issue - this should however unblock CI.
> Add a 10 minute delay before accepting nodes

- caasp-devenv
- caasp-kvm/caasp-kvm
This passes the argument through to caasp-kvm, where caasp-kvm will
not inject new code, rebuild a velum-development image, etc giving
you a "vanilla" deployment based only on the downloaded qcow.
> Allow caasp-devenv to take a --vanilla argument

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/features/03-download-kubeconfig.rb
- velum-bootstrap/spec/features/04-upgrade-admin.rb
- velum-bootstrap/spec/features/05-upgrade-minions.rb
- velum-bootstrap/spec/support/helpers.rb
If we don't do this, later checks such as this one will hang for the duration
of the wait period:
expect(page).to have_selector( ..., wait: 400)
> Velum Bootstrap: Expect HTTP 200 Status Codes

- caasp-devenv
- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf.erb
- misc-tools/extract-kernel-initrd-cmdline-args
This commit introduces a new flag that boots all the VMs with the spectre and meltdown fixes disabled.
To do that we have to instruct terraform to boot the VMs with a series of kernel params. We have also to provide libvirt a kernel and an initrd files.
These files, plus the already present kernel boot parameters, are extracted from the qcow image by a new helper tool.
This code requires latest version of terraform-libvirt-provider (I'm working on packaging it).
> Make it possible to disable meltdown and spectre patches

- misc-tools/extract-kernel-initrd-cmdline-args
This is required to make the CI more reliable...
> caasp-kvm: try to install guestfs-tools if needed

- misc-tools/extract-kernel-initrd-cmdline-args
The extraction of the initrd and kernel is going to fail if these files are already available inside of the downloads directory.
Ensure the files are deleted from downloads before trying to extract them again.
> Make extraction of files from qcow more robust

- caasp-kvm/cluster.tf.erb
For best performance, set CPU to host-passthrough mode.
> KVM: Set host-passthrough CPU mode

- misc-tools/wait-for-velum
This hack makes sure we use IPV4 and do not even try IPV6 to access velum to avoid a 10 second timeout.
> avoid a timeout on IPV6 in wait-for-velum

- k8s-e2e-tests/e2e-tests
KUBECONFIG should be explicitly passed to each kubectl invocation. We
generally avoid exporting vars in our tools, which would also work in
this case, as they make it harder to see+trace where the arguments gets
used later in the scripts.
> Ensure KUBECONFIG is passed to kubectl invocations

- caasp-kvm/tools/build-velum-image
In any case we are downloading gems from the outside (rubygems) because the
development gems are not included with the Velum package, so don't copy
gems back to development image.
Fixes the fontawesome problem.
> Do not copy gems from the packaging side as they contain invalid symlinks

- caasp-kvm/cluster.tf.erb
to avoid the error described here:
https://github.com/hashicorp/terraform/issues/11205
like: Resource 'test_resource.test' does not have attribute 'computed_list.0' for variable 'test_resource.test.*.computed_list.0'
> adopt the best-practice way to use the indexing operator

- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf.erb
- caasp-kvm/tools/build-velum-image
- misc-tools/download-image
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/features/03-download-kubeconfig.rb
- velum-bootstrap/spec/features/05-upgrade-minions.rb
- velum-bootstrap/spec/spec_helper.rb
This change will make the use of local copies of remote URL images possible even if the remote image is gone.
It will make download_file stop trying to make the given url from args canonical. 
By that we avoid the http head request in make_canonical that would fail if there is no remote file (anymore). We would not even try to download the image anyway if a local copy of the same name is there. 
Beside that, making the url canonical is not needed anyway because we use wget to download and that tool takes care of redirects.
I hope that #286 will get merged, after that I'll rebase this to get it in.
> Purify download file

- caasp-devenv
- caasp-kvm/caasp-kvm
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-remove
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/features/06-node-add.rb
- velum-bootstrap/spec/features/07-node-remove.rb
- velum-bootstrap/spec/support/helpers.rb
- velum-bootstrap/velum-interactions
```
./caasp-devenv --build -m 1 -w 1 --bootstrap
./caasp-devenv --update-deployment -m 1 -w 2
./velum-interactions --node-add
./velum-interactions --node-remove
```
https://github.com/kubic-project/jenkins-library/pull/151
> enable adding/removing nodes through caasp-kvm and velum-interactions

- velum-bootstrap/spec/support/helpers.rb
the goal was originally to have an ascending numeration for the
screenshots in the jenkins UI
but the counter only works when the whole testsuite is ran in 1
single file
in the meantime jobs got split into different files, so the counter
is reset, which renders it's purpose useless
> use unix time instead of self made counter

- velum-bootstrap/spec/features/07-node-remove.rb
5 node nightly ci failed because it found 5 nodes to remove
from http://jenkins.caasp.suse.net/job/caasp-nightly-node-remove/job/master/7/consoleFull
```
>>> Checking if node can be removed
User removes a node (FAILED - 1)
Failures:
1) Remove a Node User removes a node
Failure/Error: expect(page).to have_link(text: "Remove", count: worker_number, wait: 120)
expected to find link nil with text "Remove" 2 times, found 5 matches: "Remove", "Remove", "Remove", "Remove", "Remove". Also found "kubectl config", "", "", which matched the selector but not all filters.
```
**cc** @vitoravelino can you confirm that masters are also removable now?
> master nodes are removable now as well

- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade
Without this, it seems it wasn't running any of the job specific steps :(
Backport of https://github.com/kubic-project/automation/pull/315
> [2.0] Add empty preBootstrapBody to all periodic jenkinsfiles

- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
For conformance test jobs, we don't want to inject the latest code
from git, vanilla mode prevents this.
> K8S Conformance Jobs: Use caasp-kvm in 'vanilla' mode

- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
For conformance test jobs, we don't want to inject the latest code
from git, vanilla mode prevents this.
(cherry picked from commit c09e58b682c4498597003860c88b86eaf94360db)
> [2.1]  K8S Conformance Jobs: Use caasp-kvm in 'vanilla' mode

- jenkins-pipelines/Jenkinsfile.kube-conformance-nightly
For conformance test jobs, we don't want to inject the latest code
from git, vanilla mode prevents this.
(cherry picked from commit c09e58b682c4498597003860c88b86eaf94360db)
(cherry picked from commit 2ebfb44dfa1d2375a99ea267eb68defd22f4a323)
> [2.0] K8S Conformance Jobs: Use caasp-kvm in 'vanilla' mode

- caasp-kvm/cloud-init/admin.cfg
- caasp-kvm/cloud-init/master.cfg.tpl
- caasp-kvm/cloud-init/worker.cfg.tpl
update hostnames in cloud-init
relevant commit: 
https://github.com/kubic-project/automation/commit/e5eac687760a33267048364d778c2e8531c4d9f9
> caasp prefix has been removed from metadata

- caasp-kvm/caasp-kvm
This was accidently changed from a ordinary argument to a variable in
c841dc225ea7d248ae99a1cb121b0b1580c774b9.
> KVM: Fix parallelism flag

- testinfra/tox.ini
This allows for testing with unused/removed/etc minions. New status
types are stubbed out.
> Allow status to be passed to Testinfra

- caasp-devenv
i had some difficulties to clone all needed repos needed by other scripts.
I think having an array of github_repo can improve to manage/maintain also this repos in subprojects at least for the casp-kvm-part which is relevant for the casp-dev-env
> only by --setup option clone  fondamental github repository for kubic

- velum-bootstrap/spec/features/07-node-remove.rb
@vitoravelino @inercia can you check if this logic is sufficient?
```
if there is only 1 master
it's not removable
else
all nodes are potentially removable
```
or is there more logic behind?
> when there's only one master/worker subtract it from removables

- misc-tools/download-image
When an image is not found, we throw a cryptic error message. This
fixes that, giving a clearer error.
[misc-tools] Running shell script
+ set -o pipefail
+ ./download-image --proxy **** --location **** --type kvm channel://devel
+ tee /j/workspace/lum_PR-512-QIGXQKGO62MB6JA3Q3D4T/logs/caasp-kvm-prepare-image-caasp.log
Traceback (most recent call last):
File "./download-image", line 279, in <module>
use_channel_file(args)
File "./download-image", line 67, in use_channel_file
remote_url = get_channel_url(args)
File "./download-image", line 247, in get_channel_url
"image": parser.get_image()
File "./download-image", line 44, in get_image
return self.images.pop().strip(" ")
KeyError: 'pop from an empty set'
script returned exit code 1
(cherry picked from commit …
> [3.0] Downloader: Fix pop from empty set

- misc-tools/download-image
When an image is not found, we throw a cryptic error message. This
fixes that, giving a clearer error.
[misc-tools] Running shell script
+ set -o pipefail
+ ./download-image --proxy **** --location **** --type kvm channel://devel
+ tee /j/workspace/lum_PR-512-QIGXQKGO62MB6JA3Q3D4T/logs/caasp-kvm-prepare-image-caasp.log
Traceback (most recent call last):
File "./download-image", line 279, in <module>
use_channel_file(args)
File "./download-image", line 67, in use_channel_file
remote_url = get_channel_url(args)
File "./download-image", line 247, in get_channel_url
"image": parser.get_image()
File "./download-image", line 44, in get_image
return self.images.pop().strip(" ")
KeyError: 'pop from an empty set'
script returned exit code 1
> Downloader: Fix pop from empty set

- caasp-kvm/caasp-kvm
- caasp-kvm/tools/fix-kubelet-manifest
this already happens at build time in caasp-container-manifests
but the changes are overwritten in our devsetup, so in this case
we just need to apply them again
> patch image paths when using kubic

- caasp-kvm/cloud-init/admin.cfg
Otherwise, local modifications done to the configuration of haproxy
never applies when we create a development environment. It's kind of
a corner case, but can be confusing if you are messing with the
`haproxy` configuration and creating development environments.
> Apply local changes to the haproxy config using cloud-init

- caasp-kvm/cloud-init/admin.cfg
Otherwise, local modifications done to the configuration of haproxy
never applies when we create a development environment. It's kind of
a corner case, but can be confusing if you are messing with the
`haproxy` configuration and creating development environments.
(cherry picked from commit cc6dfbed52102faf73e53a877e9768404d44d28e)
> [3.0] Apply local changes to the haproxy config using cloud-init

- caasp-devenv
this two pkgs were hidden deps
```bash
- 
>>> [caasp-devenv] Installing CaaSP Development Environment Requiemnts
./caasp-devenv: Zeile 242: lsb-release: Kommando nicht gefunden.
>>> [caasp-devenv] Adding SUSE:CA Zypper repo
```
- make again needed for nokogiri
> add make and lsb-releases pkgs for caasp-devenv

- jenkins-pipelines/Jenkinsfile.kubic-sandbox
- velum-bootstrap/spec/spec_helper.rb
as the job is triggered on demand we need to increase the timeout
depends on https://github.com/kubic-project/jenkins-library/pull/178
> increase timeout, mainly to fetch the sandbox image

- velum-bootstrap/spec/features/03-download-kubeconfig.rb
Signed-off-by: Vítor Avelino <vavelino@suse.com>
(cherry picked from commit 813a83515a7913dd42351b74fdd59bde35da621b)
> velum-bootstrap: updated kubeconfig button name

- jenkins-pipelines/Jenkinsfile.image-cacher
- misc-files/download-urls.json
in addition to https://github.com/kubic-project/automation/pull/391 it probably helps to reduce time when triggering the sandbox CI run on demand
> add sandbox channel and cache it regularly

- misc-tools/download-image
The hardware-x86_64 image provides the required 9p*.ko modules for mounting
folders from the host machine into the vms.
> Workaround bsc#1091097: use the kubic hardware-x86_64 image.

- caasp-devenv
- velum-bootstrap/velum-interactions
Virtualization:containers has way more than we really need in it, including
massively out of date packages which are now causing problems. Move to a new
Devel:CASP:CI project which contains just what we need.
> Move away from Virtualization:containers

- Jenkinsfile.housekeeping
This repo is not shipped, so theres no reason to require bug
numbers are present.
Depends-On: https://github.com/kubic-project/jenkins-library/pull/182
> Disable bugzilla reference checks on this repo

- misc-tools/ssh-into
- misc-tools/ssh-into.README.md
SSH into KVM / OpenStack / Bare metal hosts managed by CI
The tool captures the hosts ipaddrs and a copy of environment.json from the CI run log
Examples:
```sh
$ misc-tools/ssh-into <jenkins run URL> admin
$ misc-tools/ssh-into <jenkins run URL> master -n1
$ misc-tools/ssh-into <jenkins run URL> worker -n2
```
-n  Host number, starting from 0
-e  Load environment.json from disk
-i  SSH identity / private key path
```
usage: ssh-into [-h] [-n N] [-e ENV_JSON_PATH] [-i SSHKEY] [-l LOGFILE]
[--dumpjson]
ci_run {admin,master,worker}
positional arguments:
ci_run                CI run URL
{admin,master,worker}
Target host
optional arguments:
-h, --help            show this help message and exit
-n N                  Host number (default: 0)
-e ENV_JSON_PATH, --env-json-path ENV_JSON_PATH …
```
> Add script to ssh into CI hosts

- k8s-e2e-tests/e2e-tests
cluster
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>
> Increase k8s e2e tests timeout cause this is not enought on our test

- jenkins-jobs/job-templates.yaml
Sometimes, people would use "release-2.0-foo" style branch names for
backports, which were getting matched - and too many jobs would run (and
fail, as they aren't a proper branch shared accross all repos job..)
Switch to using a regex to filter these unwated matches out
> JJB: Update branch matching to avoid unwated matches

- caasp-openstack-terraform/caasp-cluster.tf
- caasp-openstack-terraform/openstack.tfvars
With dnsentry set to 0:
Outputs:
hostname_admin = []
hostnames_masters = []
ip_admin_external = 10.84.73.105
ip_admin_internal = 10.0.1.136
ip_masters = [
10.84.73.106,
10.84.73.107,
10.84.73.114
]
ip_workers = [
10.84.73.108,
10.84.73.113,
10.84.73.112
]
With dnsentry set to 1:
Outputs:
hostname_admin = [
caasp-admin.testing.qa.caasp.suse.net.
]
hostnames_masters = [
caasp-master0.testing.qa.caasp.suse.net.
]
ip_admin_external = 10.84.73.85
ip_admin_internal = 10.0.2.24
ip_masters = [
10.84.73.84
]
ip_workers = [
10.84.73.8,
10.84.73.80,
10.84.73.86,
10.84.73.83,
10.84.73.82
> enable designate dns recordsets (on off feature based on dnsentry being set to 0 or 1)

- misc-tools/download-image
Looking for SHA256 sums in files by specific columns fails if the files'
columns are not laid out to the get_sha256 function's assumptions.
Instead, look for a length-64 hex word in the file text by regex to find
the sha256 sum. Error if no sum is found or if more than one word
matches the regex.
> download-image: Find SHA256 by regex

- velum-bootstrap/spec/spec_helper.rb
Setting js_errors errors to false hides many real errors, and leads
to confusing results as rspec will just hang forever, eventually
timing out, instead of stopping and showing the failure.
The specific error mention in the original PR is a real bug in the
product, and it generally happens only very occasially. We shouldn't
just hide it!
This reverts commit 7443fe9b50e9cf09b903f2072727fcc1e0453749.
Originally introduced in https://github.com/kubic-project/automation/pull/391
> Revert "[testing] set js_errors to false"

- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade
This allows for the job to change branch where necessary. Another later
cleanup will remove the hardcoded branch name. I'm thinking adding
the hardcode is OK given we already hardcode the update repo URL a few
lines above.
> Upgrade job: Update to use both stages

- caasp-kvm/caasp-kvm
- caasp-kvm/cluster.tf.erb
- caasp-kvm/terraform.tfvars.example
- caasp-kvm/tools/cleanup.sh
To dev and test SES on CaaSP, workers need to be able to be created with
local storage attached. Because terraform-provider-libvirt does not have
a volume attachment, ERB templating is used to add a variable number of
additional disks to worker nodes.
Allow users to specify a custom .tfvars file to use so that our dev
environment can specify its preferred overrides without modifying the
example tfvars file in automation/caasp-kvm.
> caasp-kvm: support ses team needs

- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade
Increase the frequency of the upgrade job to once every two hours. The job
currently takes approx 1.5hrs to run, so this will keep a job running
almost always.
> Increase upgrade job frequency

- jenkins-jobs/jobs.yaml
The master branch is the latest code, there is nothing to upgrade to - so
lets remove the job from that branch.
> Skip upgrade job for master

- testinfra/tests/test_common.py
- testinfra/tests/test_kubernetes_master.py
- testinfra/tests/test_kubernetes_worker.py
- testinfra/tests/test_kubic_admin.py
- testinfra/tox.ini
A dummy test that does nothing, but lets CI pass without yet having any
removed/unused tests as a testinfra.xml will  be generated with at least
one test. Remove once we have at least 1 test for each role+status
combination.
> Add dummy unused/removed testinfra tests

- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
as we have increased the admin ram in CI we need to scale down
on the addNode job
Error: cannot set up guest memory 'pc.ram': Cannot allocate memory
> addNode: reduce worker number

- environment.json.example
- testinfra/setup.py
- testinfra/tests/test_kubernetes_master.py
- testinfra/tests/test_kubernetes_worker.py
- testinfra/tests/utils.py
- velum-bootstrap/spec/features/01-setup-velum.rb
- velum-bootstrap/spec/spec_helper.rb
- velum-bootstrap/spec/support/helpers.rb
Add support for feature flags to be passed though the CI/Test tooling. This allows for tests to be more easily written for optional features - e.g. a specific CRI implementation.
It's likely easier to review each commit is isolation.
> Feature flags for testing

- caasp-kvm/tools/cleanup.sh
Added a step to remove old KVM images that are stored and kept in the downloads folder.
Signed-off-by: Vicente Zepeda Mas <vzepedamas@suse.com>
> Add step to remove old KVM images in download folder

- k8s-e2e-tests/e2e-tests
We would like to use sonobuoy command only for e2e conformance tests.
Conformance tests runs systemd-logs plugin which uses privileged security context
> Fix sonobuoy and run only e2e plugin, bsc#1104068

- jenkins-pipelines/Jenkinsfile.kube-e2e-nightly
- jenkins-pipelines/Jenkinsfile.kube-e2e-serial-nightly
- jenkins-pipelines/Jenkinsfile.kube-e2e-slow-nightly
- k8s-e2e-tests/README.md
- k8s-e2e-tests/e2e-tests
The new e2e tests take longer than the conformance tests. So I made it possible to set the wait time and increased the times for the new tests. 
I also did some minor formatting and removed a reference to an arg that no longer exists.
> Add ability to change wait time for e2e tests

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
Integration test are not passing in https://github.com/kubic-project/velum/pull/647 because of a changed text in the UI form this PR is required for the other one to run. And probably will make this build fail until the other one is in place.
> Fixes test case that is looking for outdated text in UI

- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
This test are changing a part that in this PR changes https://github.com/kubic-project/velum/pull/647
Also deleted a extra step that had a note to be removed as soon as this [bug](https://bugzilla.suse.com/show_bug.cgi?id=1050450) was fixed, didn't break anything and made the specs go 120 seconds faster.
> FIX bsc#1099985 changes test to check on standard parts of the UI

- caasp-bare-metal/deployer/deploy_testbed.py
Allow testing 4.0 ISOs in the master bare metal pipeline.
(Temporary hack to be reverted once the ISO is moved to the correct URL)
> Bare metal: add temporary ISO URL

- misc-tools/parallel-ssh
We should not be installing extra repos during CI, certainly not SLE12 repos on
Leap! Additionally,  we should avoid installing packages at all during CI and
instead bake them into the base Jenkins image.
> Remove usage of SLE Repo on Leap

- caasp-devenv
- velum-bootstrap/velum-interactions
The installation of `$DIST_PACKAGES` and `$EARLY_DIST_PACKAGES` happens
only outside of the CI, so the Jenkins base image should come
pre-baked with the correct packages. Any installation attempt that
happens during the CI should fail.
> Do not install packages during CI

- testinfra/tests/test_kubernetes_master.py
- testinfra/tests/test_kubernetes_worker.py
- testinfra/tests/test_kubic_admin.py
In the current docker package this service does no longer exist:
https://build.opensuse.org/package/view_file/Virtualization:containers/docker/docker.spec?expand=1
> Remove checking for containerd.service

- caasp-kvm/cluster.tf.erb
in the v0.5.00 of `terraform-libvirt-plugin` the API for the `libvirt_cloudinit` will change to `libvirt_cloudinit_disk`.
This PR will adapt the kubic-terraform tf files to reflect this change.
with the 0.5.0 version doing multiples time `terraform plan` with a `cloud_init_disk` resource doesn't produce anymore any resource creation for nothing, see issue https://github.com/dmacvicar/terraform-provider-libvirt/issues/313
> Adapt cloudinit api change to reflect new api in terraform-libvirt

- caasp-kvm/tools/libvirt-tool
For example, we can do a `libvirt-tool snapshot` right after the bootstrap and then `rollback` every time we want to test an orchestration from scratch...
> Added a tool for managing libvirt VMs

- caasp-kvm/caasp-kvm
I'm pretty sure the only time VPN connectivity is needed is during build, and it's mildly aggravating when destroy complains that it can't ping. :)
> only ping on build

- velum-bootstrap/spec/features/08-add-remote-registry.rb
- velum-bootstrap/spec/spec_helper.rb
- velum-bootstrap/velum-interactions
Add `spec/feature/08-add-remote-registry.rb` to `velum-bootstrap`. Using
the `velum-interactions` flag `--registry-add`, add a remote
registry to Velum. Allow the environment variables
`REMOTE_REGISTRY_NAME` and `REMOTE_REGISTRY_URL` to be overridden by the
user for setting a custom registry for their environment.
> velum-bootstrap: Add remote registry spec feature

- jenkins-jobs/job-templates.yaml
- jenkins-jobs/jobs.yaml
These will end up rendered in GitHub as:
Jenkins/Flake8/pr-head
etc instead of:
continuous-integration/jenkins/Flake8/pr-head
> JJB: Change notification-context's to be something nicer to read

- caasp-kvm/tools/cleanup.sh
Leaving the "suse-caasp-whatever" KVM image in the storage volume seems to "sometimes" prevent Terraform from assembling the cluster.  So, add those images to the list to remove in manual cleanup script.
Also:
* cleaned up the grep regex using a few `-e` options to make it a bit easier to read (and extend in the future)
* removed the unnecessary shell wrapper in the xargs command
> Add caasp-kvm release image to volume delete list

- caasp-devenv
- caasp-kvm/caasp-kvm
- caasp-openstack-heat/caasp-openstack
Validate cli options and throw error message and stop if one is not recognized.
Presently invalid cli options are silently ignored. A typo in specifying an option will cause the action not no be executed without warning.  For example:
caasp-kvm --build -m 1 -w 1 --botstrap   (notice the typo in 'botstrap' instead of 'bootstrap')
will create a cluster but will not bootstrap it. Execution looks correct, but the K8s cluster is not actually deployed.
This is particularly troublesome for beginners who don't know what is the expected output of executing an action.
Signed-off-by: Pablo Chacin <pchacin@suse.com>
> Validate cli options passed to scripts

- caasp-kvm/caasp-kvm
- caasp-kvm/tools/fix-kubelet-manifest
- jenkins-pipelines/Jenkinsfile.kubic-sle15
- misc-files/download-urls.json
- misc-tools/download-image
This PR adds a new channel `devel_15`, that will use the new `qcow2` images for SLE15 and patch the container manifests to use docker-images from `registry.suse.de`.
> Allow SLE15 as devenv

- velum-bootstrap/velum-interactions
I was running some CI but the velum-interations step fails because a sudo is missing:
>>> [velum-bootstrap] Installing Velum Interaction Requirements
grep: /boot/grub2/grub.cfg: Permission denied
> fix missing sudo in velum-interations setup

- caasp-kvm/cluster.tf.erb
- caasp-kvm/disk_caching.xsl
The unsafe policy prevent fsync from KVM VMs to be executed by the hypervisor as well. It seems to be effective as a workaround to unexpectedly high disk write latencies.
It can lead to data loss in the VM in case of power failure on the hypervisor but this is not a concern for CI testbeds.
> Set disk caching policy to "unsafe"

- caasp-devenv
The libvirt-provider from the stable terraform repository will not work with the
xml tags used in the terraform file.
> Use the unstable terraform repository.

- caasp-kvm/caasp-kvm
Perform a better cleanup with caasp-kvm --destroy
Terraform should be fixed to do the cleanup by itself.
> caasp-kvm: undefine admin VM

- caasp-devenv
Move to `stable` repo 
do we need to update something else?
> Move to stable repo V0.5.1

- k8s-pod-tests/k8s-pod-tests
Occasionally the master branch encountered the same error as in release 3.0
Already fixed in release 3.0 in #565 
```error: Scaling the resource failed with: could not update the scale for deployments.extensions default: Operation cannot be fulfilled on deployments.extensions "default": the object has been modified; please apply your changes to the latest version and try again; Current resource version 2749```
> Handle kubectl scale failures

- caasp-kvm/tools/build-velum-image
After bundler was updated to 2.0.0 from rubygems.org in 01/03/2019, velum-development:0.0, which has ruby2.1 failed to install ruby bundler because new ruby bundler requires >= ruby2.3.0 and gem installation uses highest version if not specified.
After it failed installing bundler, it does not install any dependent gems on the velum image template.
This causes to fail to deploy static pods in admin node. And cluster build fails with "Waiting for Velum to initialize". So simple solution is locking the safe version on bundler.
> Fix Issue #577: ruby bundler update

- jenkins-pipelines/Jenkinsfile.kubic-nightly-network-emulation
Make this pipeline consistent with the other ones.
To be backported to release-3.0
> Use vanilla KVM in network emulation pipeline

- caasp-hyperv/README.md
- caasp-hyperv/caasp-hyperv.ps1
This PR fixes:
* a bug with image downloading
* default values not taking into account
It also: 
* removes checksum support
* add support for vhdx images
* updates the documentation accordingly
Use  `git cherry-pick` backport a commit from master to branches
> caasp-hyperv fixes and adding support for vhdx images

- caasp-devenv
This is a backport from HEAD.
I am not sure if we need the 2nd repo on 30, i am unfamiliar with that
> BACKPORT: Move terraform-libvirt to stable repo V0.5.1

- caasp-kvm/caasp-kvm
Use `rsync --delete` to keep kvm's injected manifests directory in sync instead of `rm * %% cp -a *`.  Uses `--exclude .git**` to exclude dotfiles and directories like the original intended, but this also recursively excludes those git-related dot files (so, the .gitignore in subdirectories and similar things that don't need to be copied) while still potentially allowing other "hidden" files if needed in the future.  It also uses `-i` so only the changes are logged.
Additionally use bash's `${var:?} structure to cause the script to fail in the exceedingly unlikely event that the target directory var is undefined or empty, because if that happened, we would've started deleting at `/` (eek).
Use  `git cherry-pick` backport a commit from master to branches
- [ false ] release-2.1 
- [ false …
> Switch injection from rm/cp to rsync

- caasp-kvm/cluster.tf.erb
When using bridge network configurations you need to enable the qemu_agent = true.
Otherwise you will not retrieve the ip adresses of domains.
Fixes #574
Signed-off-by: Jürgen Löhel <jloehel@suse.com>
> Sets the qemu-agent variable to true if a bridge will be used.

- ses-openstack-terraform/ses-openstack
- suse-registry-mirror-openstack-terraform/suse-registry-mirror-openstack-terraform
After playing around with the cluster I saw that the `network_name` variable does not exist any more and is now split up into `internal_net` and `external_net`.
I hope that is valid and would appreciate a short review.
> Fix terraform variables

- velum-bootstrap/spec/features/03-download-kubeconfig.rb
- velum-bootstrap/spec/support/helpers.rb
The spec for checking the kubeconfig download was previously done
through checking an url associated with the automatic download.
A better way of checking the autoamtic download is to check the
content disposition in the response header.
> velum-bootstrap: check content disposition instead of url

- testinfra/tests/test_kubernetes_master.py
After deploying the new k8s version our infratests are failing at
the part where is parses nodes.json. The fix is very simple,
replacing 'Items' with 'items'.
Previous bevarior:
```
============================================================== FAILURES ===============================================================
_________________________ TestKubernetesMaster.test_kubernetes_cluster[ssh://master-0.devenv.caasp.suse.net] __________________________
self = <tests.test_kubernetes_master.TestKubernetesMaster object at 0x7fb097ebfa10>
host = <testinfra.host.Host object at 0x7fb098008910>
@pytest.mark.bootstrapped
def test_kubernetes_cluster(self, host):
host.run(
"kubectl cluster-info dump --output-directory=/tmp/cluster_info"
)
nodes = json.loads( …
```
> [k8s 1.13] Fix case for items in the new k8s

- k8s-e2e-tests/e2e-tests
The script `e2e-tests` will now accept parameters `--sonobuoy-image`
and `--sonobuoy-version` so it's possible to run the conformance tests
specifically for the specified sonobuoy versions.
This will typically come as a jenkins pipeline parameter, and allows us
to not modify the status of the worker other than creating containers.
Depends on: https://github.com/kubic-project/jenkins-library/pull/248
> Allow to specify a specific sonobuoy repository and version

- Jenkinsfile.codenarc
- Jenkinsfile.jenkins-jobs
The codenarc pipeline is the only one which depends on the k8s Jenkins
plugin. As such, we can use docker directly in order to be able to drop
the plugin from the server.
- Unnecessary dependency to k8s JK plugin
- Uses docker cmd directly
Use  `git cherry-pick` backport a commit from master to branches
- [ X] release-3.0
This will need backport to release-3.0 branch once it's green
> Jenkinsfile.codenarc: Use docker cmdline directly instead of k8s Jenkins plugin

- caasp-openstack-terraform/caasp-cluster.tf
This PR add the stack name to the instances names, remove unused connection resource blocks and improve the referring to the key_pair resource.
> Add stack name in vm instances and minor fixes

- velum-bootstrap/spec/features/03-download-kubeconfig.rb
- velum-bootstrap/spec/support/helpers.rb
The spec for checking the kubeconfig download was previously done
through checking an url associated with the automatic download.
A better way of checking the automatic download is to check the
content disposition in the response header.
The previous behavior to manually download kubeconfig was maintained in
order to use the kubeconfig in further tests. The only difference is
that is compatible with both GET and POST requests due to different
versions in different repos. In the future we can remove the GET and
keep only the POST one.
(cherry picked from commit 3a1afa4127ff2caa303057817e63ab3a92aa7a90)
Backport of #592
> [3.0] velum-bootstrap: check content disposition instead of url

- misc-tools/upload-image-openstack.sh
The openstack command always returns 0 if the command was successful
even when an image was not present. As such, we need to actually check
the output of this command to find out if we already have the image on
the server.
> misc-tools: upload-image-openstack: Fix conditional for glance images

- jenkins-pipelines/Jenkinsfile.kube-scaling-nightly
- jenkins-pipelines/Jenkinsfile.kubic-nightly-bare-metal
- jenkins-pipelines/Jenkinsfile.kubic-nightly-network-emulation
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-add
- jenkins-pipelines/Jenkinsfile.kubic-nightly-node-remove
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack
- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade
- jenkins-pipelines/Jenkinsfile.kubic-sandbox
This job will run the pod scaling tests in a nightly basis.
Remove the scaling tests from the rest of the pipelines.
Backported from https://github.com/kubic-project/automation/pull/614
> [3.0] Add a specific scaling pipeline

- caasp-bare-metal/deployer/environment_json.py
- caasp-hyperv/tools/generate-environment
- caasp-kvm/tools/generate-environment
- caasp-openstack-heat/tools/generate-environment
- environment.json.example
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/features/06-node-add.rb
- velum-bootstrap/spec/spec_helper.rb
Minion id had inconsistent naming `minionID` and `minionId`, and this
can lead to errors and unexpected behavior.
> Consistent minion id naming

- caasp-bare-metal/deployer/environment_json.py
- caasp-hyperv/tools/generate-environment
- caasp-kvm/tools/generate-environment
- velum-bootstrap/spec/features/02-bootstrap-cluster.rb
- velum-bootstrap/spec/features/06-node-add.rb
- velum-bootstrap/spec/spec_helper.rb
Minion id had inconsistent naming `minionID` and `minionId`, and this
can lead to errors and unexpected behavior.
(cherry picked from commit 7314757)
> [3.0] Consistent minion id naming

- k8s-e2e-tests/e2e-tests
Sometimes sonobuoy retrieve does not work, retry the retrieve command.
(cherry picked from commit 9435faa2ad4a4ef7de9375b3ee4102f759952258)
Backport of https://github.com/kubic-project/automation/pull/626
> Retry sonobuoy retrieve

- misc-tools/upload-image-openstack.sh
In order to minimize the possibility to run into a situation where a
previous image was removed but a new one was not uploaded we need to
play safe here and do the removal in the final step.
> misc-tools: upload-image-openstack: Only remove image if a new one was added

- caasp-devenv
- caasp-openstack-terraform/caasp-openstack-terraform
- caasp-openstack-terraform/tools/generate-environment
- jenkins-jobs/jobs.yaml
- jenkins-pipelines/Jenkinsfile.kubic-nightly-openstack-terraform
- misc-tools/netdata/install
- misc-tools/parallelssh/tool.py
- misc-tools/upload-image-openstack.sh
- velum-bootstrap/velum-interactions
This PR introduces caasp-openstack-terraform script which plugs into caasp-devenv to create development environments in OpenStack. The script alone can also be used by the CI to run nightly jobs. Finally, a new OpenStack pipeline was added.
> Improve Openstack terraform support

- caasp-devenv
The script ends with multiple evaluation statements and in case the
last one is false then the script exists with non-zero exit code. As
such we need to be explicit and exit with '0' at the end.
Fixes: bsc#1125050
> caasp-devenv: Add explicit exit code

- testinfra/tools/testAllRoles.sh
- What was wrong with the existing code?
- How does this PR fixes it?
ENVIRONMENT_JSON was not used before, this is just a bit cleaner.
> rename FILE variable to ENVIRONMENT_JSON in testAllRoles.sh

- caasp-openstack-terraform/caasp-openstack-terraform
If we have more than one image available for a specific version,
channel, etc when we need to sort them based on Name and fetch the top
one. The way we construct and upload our images to glance guarantees
that the build name is part of the name so the top one will always be
the most recent one
> caasp-openstack-terraform: Always use the latest image

- misc-tools/upload-image-openstack.sh
The correct variable for the iteration is 'image' so fix it. This fixes
the following problem in the CI
[...]
[+] Deleting previous SUSE CaaSP qcow2 VM image for {version=4.0,channel=devel}
./upload-image-openstack.sh: line 25: images: unbound variable
> misc-tools: upload-image-openstack: Fix wrong variable name

- velum-bootstrap/spec/features/05-upgrade-minions.rb
Also in ci we were displaying this which can led to confusion.
> Fix feature name. Feature concern minion

- jenkins-pipelines/Jenkinsfile.kubic-nightly-upgrade
There is no good reason why we should run the job every two hours.
We should treat it like the rest of the dailies and run it once a day.
> jenkins-pipelines: upgrade: Run the upgrade job once a day

- caasp-openstack-terraform/caasp-cluster.tf
- caasp-openstack-terraform/caasp-openstack-terraform
- caasp-openstack-terraform/terraform.tfvars
- What was wrong with the existing code?
- How does this PR fixes it?
This allows us to attach volume to worker nodes so we can test storage solutions on top of CaaSP.
This also change the "default" flavors for masters and workers from `m1.large` to `m1.medium`. 4gb and 2vcpu is what we use on other platforms, this is enough.
> Add support for cinder volumes to workers in openstack terraform
